Feature - Roadmap(no UI)
pranav7/cadet-app pull request #45
Opened 2020-02-07 21:00 UTC by srikar0896

2020-02-17 20:27 UTC, pranav7 requested changes

2020-02-17 20:27 UTC, pranav7 commented on app/models/company.rb
> +  def is_cadet_app?
```suggestion
  def cadet_app?
```

2020-02-17 20:27 UTC, pranav7 commented on app/models/company.rb
> +    subdomain === "feedback"
```suggestion
    subdomain == "feedback"
```

2020-02-17 20:27 UTC, pranav7 commented on app/controllers/roadmap_controller.rb
> +        Post.joins(:board).where(status: status, private: false, boards: { roadmap_enabled: true })
I think this might be a problem. This will fetch all posts from other companies as well, what we need is only the posts for the current company. The issue is the `posts` table does not have a relation with the company (which I think we should have): https://github.com/pranav7/cadet-app/blob/59bc503021a611bf94b0ef609e49a6ad81fdf2c3/db/schema.rb#L144-L158

Let's discuss this in a call as well.

2020-02-21 12:55 UTC, pranav7 commented on app/controllers/roadmaps_controller.rb
> +    end
We would also want to check that the current user signed in is an admin on cadet, so that this is not visible to anyone else

2020-02-22 11:54 UTC, pranav7 commented on app/controllers/roadmaps_controller.rb
> +    end
```ruby
redirect_to(root_path) unless current_company.cadet_app?
```

2020-02-22 12:45 UTC, pranav7 commented on config/routes.rb
> +  resources :boards, path: "/" do
```suggestion
  resources :boards, path: "" do
```
Can we remove this change?

2020-02-22 12:45 UTC, pranav7 commented on db/schema.rb
> +    t.index ["email", "company_id"], name: "index_users_on_email_and_company_id", unique: true
I will have to fix this schema file before merging

2020-02-22 12:47 UTC, pranav7 commented on spec/controllers/roadmaps_controller_spec.rb
> +    end
@srikar0896 We should have also have a spec for checking that posts from private boards are visible to Admins if they are signed in?

2020-02-22 12:52 UTC, pranav7 commented on spec/controllers/roadmaps_controller_spec.rb
> +  let!(:post3) { create :post, board: private_board, status: 1 }
Let's use factory girl traits here instead of hard coding the status: https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#traits

We can probably have a trait for each status of the post

```ruby
# factories/post.rb
FactoryGirl.define do
  factory :post do
    title "My Awesome Post Title"
    board
    content_attributes { { body: "Post Content" } }

    trait :planend do
      status Post.statuses[:planned]
    end
  end
end
```

```suggestion
  let!(:post3) { create :post, board: private_board, :planned }
```

2020-02-24 10:33 UTC, pranav7 commented on spec/controllers/roadmaps_controller_spec.rb
> +  let(:private_board) { create :board, company: company1, private: true }
@srikar0896 how about adding a trait for private boards? :)

2020-02-24 10:34 UTC, srikar0896 commented on config/routes.rb
> +  resources :boards, path: "/" do
@pranav7 not making any change in this as you are working on this.

2020-02-24 10:35 UTC, srikar0896 commented on spec/controllers/roadmaps_controller_spec.rb
> +    end
Done.

2020-02-24 10:35 UTC, srikar0896 commented on spec/controllers/roadmaps_controller_spec.rb
> +  let(:private_board) { create :board, company: company1, private: true }
will do.

2020-02-24 10:37 UTC, srikar0896 commented on spec/controllers/roadmaps_controller_spec.rb
> +  let!(:post3) { create :post, board: private_board, status: 1 }
done

2020-02-24 20:08 UTC, pranav7 commented
A couple of things before merging

- [x] Top level navigation should not be visible if the feature is disabled
- [x] Mobile navigation should not be visible if the feature is disabled
- [x] Board settings to enable roadmap should only be visible if the feature is available

2020-02-24 20:11 UTC, pranav7 commented
> Mobile navigation should not be visible if the feature is disabled

Removing this for now, let's add it back once we have merged this for Cadet

2020-02-24 20:17 UTC, merged