Bugfix - Current company in intercom auth callback
pranav7/cadet-app pull request #57
Opened 2020-03-17 12:17 UTC by srikar0896

- Retrieve company through app_id in Intercom authentication callback
- Change the style of the `Authorize intercom` button

2020-03-17 13:02 UTC, pranav7 commented on app/views/admin/integrations/show.html.slim
> +            - unless not @intercom_access_token
@srikar0896 What will `unless not` do?
Do we want to only display this button if the user does not have an `intercom_access_token`? If yes, this wouldn't work because you are negating a negation :)

2020-03-17 13:04 UTC, pranav7 commented on app/controllers/users/omniauth_callbacks_controller.rb
> +    company.company_setting.save!
Let's add some tests for this endpoint? Unlike earlier, with tests, we would have caught the error in development, and not in production :)

2020-03-17 13:06 UTC, pranav7 commented
@srikar0896 Left some comments for you here! It should be quick. Also, It would be nice to also name our Pull Requests better, it helps in searching for older pull requests for reference.

2020-03-18 10:50 UTC, srikar0896 commented on app/views/admin/integrations/show.html.slim
> +            - unless not @intercom_access_token
forgot to remove 😅

2020-03-18 11:22 UTC, pranav7 commented on spec/controllers/omniauth_callbacks_controller_spec.rb
> +RSpec.describe OmniauthCallbacksController, type: :controller do
Ideally, spec files should have similar paths to the files they are testing, in this case:
`spec/controllers/users/omniauth_callbacks_controller_spec.rb`

```suggestion
RSpec.describe Users::OmniauthCallbacksController, type: :controller do
```

2020-03-18 17:42 UTC, pranav7 commented on spec/controllers/omniauth_callbacks_controller_spec.rb
> +    set_omniauth_intercom
```suggestion
    mock_omniauth_intercom
```

2020-03-18 17:42 UTC, pranav7 requested changes

2020-03-18 17:42 UTC, pranav7 commented on spec/controllers/omniauth_callbacks_controller_spec.rb
> +    get user_intercom_omniauth_authorize_path
We should probably move these calls to the `it` block.
```suggestion
    set_omniauth_intercom
    get user_intercom_omniauth_authorize_path
```

2020-03-18 18:50 UTC, pranav7 commented on spec/controllers/users/omniauth_callbacks_controller_spec.rb
> +    it "redirects to root path" do
```suggestion
    it "redirects to integrations page" do
```

2020-03-19 17:06 UTC, merged