Post update service
pranav7/cadet-app pull request #86
Opened 2020-04-21 18:41 UTC by srikar0896

Tracking issue: https://github.com/pranav7/cadet-app/issues/87

- service for updating a post
- track `status_changed_event` if the status of the post has changed
- Add constants for event_types, and visibility

2020-04-21 18:55 UTC, srikar0896 commented on app/lib/posts/update.rb
> +          # event_type: Constants::EventTypes::STATUS_CHANGED,
@pranav7 unable to use constants here, throws `uninitialized constant Constants`. Any idea why?

2020-04-22 17:05 UTC, pranav7 commented on app/lib/constants/visibility.rb
> +module Constants::VisibilityTypes
This can just be Visibility

```suggestion
module Constants::Visibility
```

2020-04-22 17:28 UTC, pranav7 commented on app/lib/constants/visibility.rb
> +  PRIVATE = 'private'
These should also ideally be numbers

```suggestion
  PUBLIC = 0
  PRIVATE = 1
```

2020-04-22 17:30 UTC, pranav7 commented on app/lib/posts/update.rb
> +          # event_type: Constants::EventTypes::STATUS_CHANGED,
Not sure what's up with this, I was able to access it in the console

```ruby
➜  cadet-app git:(post_update_service) ✗ rails c
Running via Spring preloader in process 92554
Loading development environment (Rails 5.2.3)
[1] pry(main)> Constants::EventTypes::STATUS_CHANGED
=> 0
```

2020-04-23 17:49 UTC, pranav7 commented on app/lib/posts/update.rb
> +    attr_reader :post, :params
Let's either remove this, or add all the other params

2020-04-23 17:51 UTC, pranav7 commented on app/lib/posts/update.rb
> +      Votes::Create.run(post: @post, voter: voter)
```suggestion
      Votes::Create.run!(post: @post, voter: voter)
```

2020-04-23 17:53 UTC, pranav7 commented on app/lib/posts/update.rb
> +
If the user id changes we need to record a vote

2020-04-27 17:39 UTC, pranav7 commented on app/lib/posts/update.rb
> +      ActiveRecord::Base.transaction do
We should only log activity if the status is being changed. We should probably add a test for this!

```suggestion
    def log_activity
      return if @post.status == @status
    
      ActiveRecord::Base.transaction do
```

2020-04-28 09:24 UTC, pranav7 requested changes

2020-04-28 09:24 UTC, pranav7 commented on spec/lib/posts/update_spec.rb
> +    end
In this test, we never test if the vote was actually recorded :)

2020-04-28 09:24 UTC, pranav7 commented on spec/lib/posts/update_spec.rb
> +    end
You can just do this in the `before .. do` block above.

2020-04-28 09:24 UTC, pranav7 commented on spec/lib/posts/update_spec.rb
> +    end
This as well, you can just set this in the first `before ... do` block.

2020-04-28 09:24 UTC, pranav7 commented on spec/lib/posts/update_spec.rb
> +    end
I think if you add this to your expect statement, it should be enough.

```ruby
expect(requester.voted?(post)).to eq(true)
```

2020-04-28 09:24 UTC, pranav7 commented on spec/lib/posts/update_spec.rb
> +      end
You can just do this here, instead of declaring the `subject` again.

```suggestion
let(:status) { nil }
```

2020-04-28 17:54 UTC, srikar0896 commented on spec/lib/posts/update_spec.rb
> +    end
doing this explicitly in each case because I want to test some cases with non-admin users to validate the permissions

2020-04-28 17:57 UTC, srikar0896 commented on spec/lib/posts/update_spec.rb
> +      end
this subject is different from the other subject which is already defined. This subject is to test the scenario where "activity log must not be created if the status is not changed". For that, I have created a new subject with `status: post.status`

2020-04-28 18:02 UTC, srikar0896 commented on spec/lib/posts/update_spec.rb
> +    it "should throw Insufficient permissions error" do
@pranav7 here I don't want to login as admin, hence don't want to do in the before...do block.
```
before do
  Current.user = admin
end
```

2020-04-29 17:31 UTC, pranav7 commented on db/migrate/20200415185259_create_activity_logs.rb
> +      t.index [:post_id, :company_id]
@srikar0896 Can you revert this change? I actually thought it might be fine to just keep an index on `post_id` here for now. This would help us with the query generated by the below code

```ruby
post.activity_logs
```

2020-04-30 16:54 UTC, merged