Track Comment Created Events
pranav7/cadet-app pull request #89
Opened 2020-04-30 18:04 UTC by srikar0896

- Added a comment creation service
- Creates Activity Log when a comment is created
- Creates `Comment Created Event` when a comment is created

2020-04-30 18:12 UTC, srikar0896 commented on app/lib/comments/base.rb
> +      if (@is_private and not(Current.user.admin_of?(Current.company)))
```suggestion
      if (@is_private and !Current.user.admin_of?(Current.company))
```

2020-05-01 17:16 UTC, pranav7 requested changes

2020-05-01 17:16 UTC, pranav7 commented on app/lib/comments/base.rb
> +    def self.run!(post:, is_private:, content:)
We should also accept `commenter_id` as an attribute, and let the caller decide who becomes the commenter.

2020-05-01 17:16 UTC, pranav7 commented on app/lib/comments/base.rb
> +    end
```suggestion
    def initialize(post:, commenter:, is_private:, content:)
      @post = post
      @is_private = is_private
      @content = content
      @commenter = commenter || Current.user
    end
```

2020-05-01 17:16 UTC, pranav7 commented on app/lib/comments/create.rb
> +      comment.commenter = Current.user
```suggestion
      comment.commenter = commenter
```

2020-05-01 17:16 UTC, pranav7 commented on app/lib/comments/create.rb
> +        user_id: Current.user.id,
If you are setting the `commenter` below, this is not needed.

2020-05-01 17:16 UTC, pranav7 commented on app/lib/comments/create.rb
> +    end
We should put all of this inside a transaction to make sure ActivityLog only gets created if Comment is created.

2020-05-02 09:42 UTC, pranav7 commented on app/lib/comments/create.rb
> +      ActiveRecord::Base.transaction do
Instead of wrapping this in a `transaction`, we should rather wrap the code in `create_comment` in a `transaction`. That would mean creating a comment, activity log and add the current user to the company would all  run in one transaction

2020-05-02 09:42 UTC, pranav7 commented on app/lib/comments/create.rb
> +      Current.user.companies << Current.company unless Current.user.part_of?(Current.company)
```suggestion
      ActiveRecord::Base.transaction do
      comment = @post.comments.new(
        post_id: @post.id,
        content_attributes: @content,
        private: @is_private
      )
      comment.commenter = @commenter
      comment.save

      log_activity(comment)
      Current.user.companies << Current.company unless Current.user.part_of?(Current.company)
      end
```

2020-05-05 17:37 UTC, pranav7 commented on app/lib/comments/create.rb
> +      comment.save
`comment.save!`

2020-05-06 08:45 UTC, merged